<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModalCalendarNotification.Core\ModalCalendarNotification.Core.csproj" />
    <ProjectReference Include="..\ModalCalendarNotification.Data\ModalCalendarNotification.Data.csproj" />
    <ProjectReference Include="..\ModalCalendarNotification.CalendarProviders\ModalCalendarNotification.CalendarProviders.csproj" />
    <ProjectReference Include="..\ModalCalendarNotification.UI\ModalCalendarNotification.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="CompareNETObjects" />
  </ItemGroup>
</Project>
